name: morning
on:
  schedule:
  - cron:  '0 0 * * *'
  workflow_dispatch:

jobs:
  send_message:
    runs-on: ubuntu-latest
    name: send morning to my girlfriend

    steps:
    - name: checkout
      uses: actions/checkout@v3
      with:
        ref: master

    - name: sender
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'
        architecture: 'x64'
    - run: pip install -r ./requirements.txt && python ./main.py

    env:
      APP_ID: ${{ secrets.APP_ID }}
      APP_SECRET: ${{ secrets.APP_SECRET }}
      TEMPLATE_ID: ${{ secrets.TEMPLATE_ID }}
      TEMPLATE_ID2: ${{ secrets.TEMPLATE_ID2 }}
      USER_ID: ${{ secrets.USER_ID }} # 女方微信假id
      USER_ID2: ${{ secrets.USER_ID2 }} # 男方微信假id
      START_DATE: ${{ secrets.START_DATE }} # 恋爱开始日
      BIRTHDAY: ${{ secrets.BIRTHDAY }} # 女方生日
      BIRTHDAY2: ${{ secrets.BIRTHDAY2 }} # 男方生日
      CITY: ${{ secrets.CITY }} # 女方城市
      CITY2: ${{ secrets.CITY2 }} # 男方城市
      ASTRO: ${{ secrets.ASTRO }} # 女方星座
      ASTRO2: ${{ secrets.ASTRO2 }} # 男方星座
      API_KEY_LUCKY: ${{ secrets.API_KEY_LUCKY }} 
